// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ClientPortal.PRAT.Acceptance.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Documents page")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("Documents")]
    public partial class DocumentsPageFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "Documents"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Documents page", "  As a registered user\r\n  I want to be able to navigate to the Documents page", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
            await testRunner.GivenAsync("the user navigates to the Client Portal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
            await testRunner.AndAsync("the user is logged in", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
        }
        
        private static global::Io.Cucumber.Messages.Types.Source SourceFunc()
        {
            return new global::Io.Cucumber.Messages.Types.Source("Features/Documents.feature", "@Documents\r\nFeature: Documents page\r\n  As a registered user\r\n  I want to be able " +
                    "to navigate to the Documents page\r\n\r\n  Background:\r\n    Given the user navigates" +
                    " to the Client Portal\r\n    And the user is logged in\r\n\r\n  # @Smoke\r\n  # Scenario" +
                    ": Documents Page Check\r\n  #   When the user clicks the \"My documents\" menu link\r" +
                    "\n  #   Then the user navigates to the \"My documents\" page\r\n\r\n  @Smoke\r\n  Scenari" +
                    "o Outline: User is able to filter documents\r\n    Given the user clicks the \"My d" +
                    "ocuments\" menu link\r\n    When the user applies a \"<filter>\" on the Documents\r\n  " +
                    "  Then the user should only see the right \"<count>\"\r\n    And the \"<list>\" of doc" +
                    "uments\r\n    Examples:\r\n      | filter       | count | list                      " +
                    "                                                                        |\r\n     " +
                    " | All          | 6     | Test, Mortgage Provider List, Making more of your mone" +
                    "y, Defect106224HO, COB Booklet, COB Booklet |\r\n      | Read         | 2     | Mo" +
                    "rtgage Provider List, Making more of your money                                 " +
                    "                |\r\n      | Unread       | 3     | Defect106224HO, COB Booklet, C" +
                    "OB Booklet                                                          |\r\n      | M" +
                    "y uploads   | 1     | Test                                                      " +
                    "                                        |\r\n      | Newest first | 6     | Test, " +
                    "Mortgage Provider List, Making more of your money, Defect106224HO, COB Booklet, " +
                    "COB Booklet |\r\n      | Oldest first | 6     | COB Booklet, COB Booklet, Defect10" +
                    "6224HO, Making more of your money, Mortgage Provider List, Test |\r\n      | Title" +
                    " (A-Z)  | 6     | COB Booklet, COB Booklet, Defect106224HO, Making more of your " +
                    "money, Mortgage Provider List, Test |\r\n      | Title (Z-A)  | 6     | Test, Mort" +
                    "gage Provider List, Making more of your money, Defect106224HO, COB Booklet, COB " +
                    "Booklet |", global::Io.Cucumber.Messages.Types.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN);
        }
        
        private static global::Io.Cucumber.Messages.Types.GherkinDocument GherkinDocumentFunc()
        {
            return new global::Io.Cucumber.Messages.Types.GherkinDocument("Features/Documents.feature", new global::Io.Cucumber.Messages.Types.Feature(new global::Io.Cucumber.Messages.Types.Location(2, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(1, new System.Nullable<long>(1)), "@Documents", "3936857bb0b32a51b1c0114943f8f269")}), "en-US", "Feature", "Documents page", "  As a registered user\r\n  I want to be able to navigate to the Documents page", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.FeatureChild>(new global::Io.Cucumber.Messages.Types.FeatureChild[] {
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, new global::Io.Cucumber.Messages.Types.Background(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(3)), "Background", "", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the user navigates to the Client Portal", null, null, "1753ae329ab48f50b5960c3b41b4f5fe"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(8, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the user is logged in", null, null, "7655e6bfd76f4851b9e301da670625c1")}), "51e196a7e16e6f57a831424f717c4e69"), null),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(3)), "@Smoke", "1bb4f307bb933b53a6c47a0f83d848bc")}), "Scenario Outline", "User is able to filter documents", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the user clicks the \"My documents\" menu link", null, null, "fabd29d7cc5bd55eb8d49715c3a3f1e3"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "the user applies a \"<filter>\" on the Documents", null, null, "567043ec0cc6475ba0af1d1bc34d3d18"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the user should only see the right \"<count>\"", null, null, "c5a8cdc97da528519f40bf1c22f241bd"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the \"<list>\" of documents", null, null, "4151f7a0cd04fb54a4bf74d0c016df73")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[] {
                                                    new global::Io.Cucumber.Messages.Types.Examples(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Examples", "", "", new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(22, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(22, new System.Nullable<long>(9)), "filter"),
                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(22, new System.Nullable<long>(24)), "count"),
                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(22, new System.Nullable<long>(32)), "list")}), "9e003fa511b3bc5a94357cef52a1b071"), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableRow>(new global::Io.Cucumber.Messages.Types.TableRow[] {
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(9)), "All"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(24)), "6"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(32)), "Test, Mortgage Provider List, Making more of your money, Defect106224HO, COB Book" +
                                                                                            "let, COB Booklet")}), "de93bf51b7b4c254b561c86a24de44c4"),
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(9)), "Read"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(24)), "2"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(32)), "Mortgage Provider List, Making more of your money")}), "c0f1ac8f0acaa6598baa745278bfdbe3"),
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(9)), "Unread"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(24)), "3"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(32)), "Defect106224HO, COB Booklet, COB Booklet")}), "eaaf6462bb191552acf5cadd8d075d7c"),
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(26, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(26, new System.Nullable<long>(9)), "My uploads"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(26, new System.Nullable<long>(24)), "1"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(26, new System.Nullable<long>(32)), "Test")}), "4dfcfc4cd47b8457a8ada1ec889ffecb"),
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(9)), "Newest first"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(24)), "6"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(32)), "Test, Mortgage Provider List, Making more of your money, Defect106224HO, COB Book" +
                                                                                            "let, COB Booklet")}), "f8c4b80fd0520858b3778dac9ce267e1"),
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(28, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(28, new System.Nullable<long>(9)), "Oldest first"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(28, new System.Nullable<long>(24)), "6"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(28, new System.Nullable<long>(32)), "COB Booklet, COB Booklet, Defect106224HO, Making more of your money, Mortgage Pro" +
                                                                                            "vider List, Test")}), "c0f3181e5dc26757b5eb5e65e0310691"),
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(29, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(29, new System.Nullable<long>(9)), "Title (A-Z)"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(29, new System.Nullable<long>(24)), "6"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(29, new System.Nullable<long>(32)), "COB Booklet, COB Booklet, Defect106224HO, Making more of your money, Mortgage Pro" +
                                                                                            "vider List, Test")}), "ed32ddd86435e6529cff7084a13d6f20"),
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(30, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(30, new System.Nullable<long>(9)), "Title (Z-A)"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(30, new System.Nullable<long>(24)), "6"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(30, new System.Nullable<long>(32)), "Test, Mortgage Provider List, Making more of your money, Defect106224HO, COB Book" +
                                                                                            "let, COB Booklet")}), "d33b2b88b73f405091b028ff0147dbc5")}), "7cdee4db051f495a8f0e1f803fb4f8b5")}), "a44af0c385c06f5b823f457f7cb36e0b"))})), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Comment>(new global::Io.Cucumber.Messages.Types.Comment[] {
                            new global::Io.Cucumber.Messages.Types.Comment(new global::Io.Cucumber.Messages.Types.Location(10, new System.Nullable<long>(1)), "  # @Smoke"),
                            new global::Io.Cucumber.Messages.Types.Comment(new global::Io.Cucumber.Messages.Types.Location(11, new System.Nullable<long>(1)), "  # Scenario: Documents Page Check"),
                            new global::Io.Cucumber.Messages.Types.Comment(new global::Io.Cucumber.Messages.Types.Location(12, new System.Nullable<long>(1)), "  #   When the user clicks the \"My documents\" menu link"),
                            new global::Io.Cucumber.Messages.Types.Comment(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(1)), "  #   Then the user navigates to the \"My documents\" page")}));
        }
        
        private static global::System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle> PicklesFunc()
        {
            return new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Pickle>(new global::Io.Cucumber.Messages.Types.Pickle[] {
                        new global::Io.Cucumber.Messages.Types.Pickle("8f6adf1c780ffa58ae01bf0d03cab74f", "Features/Documents.feature", "User is able to filter documents", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1753ae329ab48f50b5960c3b41b4f5fe"}), "dc8b846c7bdd3052a3f512c3068d0258", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user navigates to the Client Portal"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "7655e6bfd76f4851b9e301da670625c1"}), "2f84f598899cda57aa0ab4a2cb0903a7", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user is logged in"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "fabd29d7cc5bd55eb8d49715c3a3f1e3",
                                                        "de93bf51b7b4c254b561c86a24de44c4"}), "bbceb5531b95a15381b4c4b2f3e347b5", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user clicks the \"My documents\" menu link"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "567043ec0cc6475ba0af1d1bc34d3d18",
                                                        "de93bf51b7b4c254b561c86a24de44c4"}), "eedcd1ce37ce8c5ca4a4e61056d0cbdb", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the user applies a \"All\" on the Documents"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c5a8cdc97da528519f40bf1c22f241bd",
                                                        "de93bf51b7b4c254b561c86a24de44c4"}), "83dadd55f5a5085e91dda01c9a75272f", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the user should only see the right \"6\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "4151f7a0cd04fb54a4bf74d0c016df73",
                                                        "de93bf51b7b4c254b561c86a24de44c4"}), "ea598a44232fd953802710108e4a2a87", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the \"Test, Mortgage Provider List, Making more of your money, Defect106224HO, COB" +
                                                " Booklet, COB Booklet\" of documents")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Documents", "3936857bb0b32a51b1c0114943f8f269"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Smoke", "1bb4f307bb933b53a6c47a0f83d848bc")}), new System.Collections.Generic.List<string>(new string[] {
                                        "a44af0c385c06f5b823f457f7cb36e0b",
                                        "de93bf51b7b4c254b561c86a24de44c4"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("88756884e74cbe53a5aeebfeaca60829", "Features/Documents.feature", "User is able to filter documents", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1753ae329ab48f50b5960c3b41b4f5fe"}), "6cdedcfb30a1f957906db66b11be372a", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user navigates to the Client Portal"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "7655e6bfd76f4851b9e301da670625c1"}), "0a600e8c4ddb8c599160cee62d3be861", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user is logged in"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "fabd29d7cc5bd55eb8d49715c3a3f1e3",
                                                        "c0f1ac8f0acaa6598baa745278bfdbe3"}), "3b38cd885b4bb553af2efee4b8144fc5", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user clicks the \"My documents\" menu link"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "567043ec0cc6475ba0af1d1bc34d3d18",
                                                        "c0f1ac8f0acaa6598baa745278bfdbe3"}), "90f086624d498c5b961d0558f0b8edbe", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the user applies a \"Read\" on the Documents"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c5a8cdc97da528519f40bf1c22f241bd",
                                                        "c0f1ac8f0acaa6598baa745278bfdbe3"}), "ef5ad4211f9e8f5da8f0a80d2e6bfe2d", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the user should only see the right \"2\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "4151f7a0cd04fb54a4bf74d0c016df73",
                                                        "c0f1ac8f0acaa6598baa745278bfdbe3"}), "df3c4607fbfb0b56b8be9c48830db297", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the \"Mortgage Provider List, Making more of your money\" of documents")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Documents", "3936857bb0b32a51b1c0114943f8f269"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Smoke", "1bb4f307bb933b53a6c47a0f83d848bc")}), new System.Collections.Generic.List<string>(new string[] {
                                        "a44af0c385c06f5b823f457f7cb36e0b",
                                        "c0f1ac8f0acaa6598baa745278bfdbe3"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("1b5e3c4d7f7e7c5087653b434799b2b6", "Features/Documents.feature", "User is able to filter documents", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1753ae329ab48f50b5960c3b41b4f5fe"}), "4e2f7fd7224e1b599a8a20af27e31fc0", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user navigates to the Client Portal"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "7655e6bfd76f4851b9e301da670625c1"}), "f6a6322cec84365984b000b42ca0dc7b", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user is logged in"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "fabd29d7cc5bd55eb8d49715c3a3f1e3",
                                                        "eaaf6462bb191552acf5cadd8d075d7c"}), "8a71911e0010965db792c31b40143b95", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user clicks the \"My documents\" menu link"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "567043ec0cc6475ba0af1d1bc34d3d18",
                                                        "eaaf6462bb191552acf5cadd8d075d7c"}), "5e01723a3cc26955b70b76c0d9e7c0a2", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the user applies a \"Unread\" on the Documents"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c5a8cdc97da528519f40bf1c22f241bd",
                                                        "eaaf6462bb191552acf5cadd8d075d7c"}), "99984881baff1e53be859407a42e9eae", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the user should only see the right \"3\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "4151f7a0cd04fb54a4bf74d0c016df73",
                                                        "eaaf6462bb191552acf5cadd8d075d7c"}), "40e6075f7fba2953bd12720cbfcaf4db", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the \"Defect106224HO, COB Booklet, COB Booklet\" of documents")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Documents", "3936857bb0b32a51b1c0114943f8f269"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Smoke", "1bb4f307bb933b53a6c47a0f83d848bc")}), new System.Collections.Generic.List<string>(new string[] {
                                        "a44af0c385c06f5b823f457f7cb36e0b",
                                        "eaaf6462bb191552acf5cadd8d075d7c"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("2170e5170c36c25b8c141375dc80d789", "Features/Documents.feature", "User is able to filter documents", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1753ae329ab48f50b5960c3b41b4f5fe"}), "28ec2eded234f553b5f8f01777fe0839", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user navigates to the Client Portal"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "7655e6bfd76f4851b9e301da670625c1"}), "02d58cbf11366f59a6cff31fdf6391b9", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user is logged in"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "fabd29d7cc5bd55eb8d49715c3a3f1e3",
                                                        "4dfcfc4cd47b8457a8ada1ec889ffecb"}), "2d07a07d708e5a538cebe506977fc4d3", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user clicks the \"My documents\" menu link"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "567043ec0cc6475ba0af1d1bc34d3d18",
                                                        "4dfcfc4cd47b8457a8ada1ec889ffecb"}), "e6a9ec4d57952f519af244831ba5c57f", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the user applies a \"My uploads\" on the Documents"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c5a8cdc97da528519f40bf1c22f241bd",
                                                        "4dfcfc4cd47b8457a8ada1ec889ffecb"}), "8ec4fa6ed3918659a4c14540461387d8", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the user should only see the right \"1\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "4151f7a0cd04fb54a4bf74d0c016df73",
                                                        "4dfcfc4cd47b8457a8ada1ec889ffecb"}), "af20334907e8f55eb516de2a18ed716d", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the \"Test\" of documents")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Documents", "3936857bb0b32a51b1c0114943f8f269"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Smoke", "1bb4f307bb933b53a6c47a0f83d848bc")}), new System.Collections.Generic.List<string>(new string[] {
                                        "a44af0c385c06f5b823f457f7cb36e0b",
                                        "4dfcfc4cd47b8457a8ada1ec889ffecb"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("13cbe973b09531558c4d57587fc41e64", "Features/Documents.feature", "User is able to filter documents", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1753ae329ab48f50b5960c3b41b4f5fe"}), "585793a4d0566e53a02218dbb9d2d836", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user navigates to the Client Portal"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "7655e6bfd76f4851b9e301da670625c1"}), "8f6c09d710e5ef5d8309a2c65f425d6b", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user is logged in"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "fabd29d7cc5bd55eb8d49715c3a3f1e3",
                                                        "f8c4b80fd0520858b3778dac9ce267e1"}), "bc965e2be8bca957b376a1b5ec947d89", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user clicks the \"My documents\" menu link"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "567043ec0cc6475ba0af1d1bc34d3d18",
                                                        "f8c4b80fd0520858b3778dac9ce267e1"}), "21f66b179f05e05f9832f67f4ee9c740", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the user applies a \"Newest first\" on the Documents"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c5a8cdc97da528519f40bf1c22f241bd",
                                                        "f8c4b80fd0520858b3778dac9ce267e1"}), "55a7a93f7dc84752b734cee32b8d938c", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the user should only see the right \"6\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "4151f7a0cd04fb54a4bf74d0c016df73",
                                                        "f8c4b80fd0520858b3778dac9ce267e1"}), "5fc72b8f3ad5535493079ae9fc48288e", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the \"Test, Mortgage Provider List, Making more of your money, Defect106224HO, COB" +
                                                " Booklet, COB Booklet\" of documents")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Documents", "3936857bb0b32a51b1c0114943f8f269"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Smoke", "1bb4f307bb933b53a6c47a0f83d848bc")}), new System.Collections.Generic.List<string>(new string[] {
                                        "a44af0c385c06f5b823f457f7cb36e0b",
                                        "f8c4b80fd0520858b3778dac9ce267e1"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("a4bf440029c72a5ab004a39777190f93", "Features/Documents.feature", "User is able to filter documents", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1753ae329ab48f50b5960c3b41b4f5fe"}), "bd8785e22f4a925a81af4c6eb783c0cf", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user navigates to the Client Portal"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "7655e6bfd76f4851b9e301da670625c1"}), "d57d10624c489a5e9aac19d9cbce310b", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user is logged in"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "fabd29d7cc5bd55eb8d49715c3a3f1e3",
                                                        "c0f3181e5dc26757b5eb5e65e0310691"}), "adf0df703056165489c48c20a72eca9e", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user clicks the \"My documents\" menu link"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "567043ec0cc6475ba0af1d1bc34d3d18",
                                                        "c0f3181e5dc26757b5eb5e65e0310691"}), "ca66d614cbe0ad5daf26a78867abc28e", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the user applies a \"Oldest first\" on the Documents"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c5a8cdc97da528519f40bf1c22f241bd",
                                                        "c0f3181e5dc26757b5eb5e65e0310691"}), "96f75188bfbbdc5d88ef98409c56b187", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the user should only see the right \"6\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "4151f7a0cd04fb54a4bf74d0c016df73",
                                                        "c0f3181e5dc26757b5eb5e65e0310691"}), "cf372aed1b335454bf0cd3ec31a5f7f7", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the \"COB Booklet, COB Booklet, Defect106224HO, Making more of your money, Mortgag" +
                                                "e Provider List, Test\" of documents")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Documents", "3936857bb0b32a51b1c0114943f8f269"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Smoke", "1bb4f307bb933b53a6c47a0f83d848bc")}), new System.Collections.Generic.List<string>(new string[] {
                                        "a44af0c385c06f5b823f457f7cb36e0b",
                                        "c0f3181e5dc26757b5eb5e65e0310691"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("6a467abad06ebd5eb5b1d3782cb66142", "Features/Documents.feature", "User is able to filter documents", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1753ae329ab48f50b5960c3b41b4f5fe"}), "2a85df53b8a6795d99f3cb059a9f252b", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user navigates to the Client Portal"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "7655e6bfd76f4851b9e301da670625c1"}), "122396915be5dc5aaeb30027a287b215", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user is logged in"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "fabd29d7cc5bd55eb8d49715c3a3f1e3",
                                                        "ed32ddd86435e6529cff7084a13d6f20"}), "92078724249d1258895d4e64cac5e72e", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user clicks the \"My documents\" menu link"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "567043ec0cc6475ba0af1d1bc34d3d18",
                                                        "ed32ddd86435e6529cff7084a13d6f20"}), "a4dd406ae45dc4599c0a09a37c7df3d7", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the user applies a \"Title (A-Z)\" on the Documents"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c5a8cdc97da528519f40bf1c22f241bd",
                                                        "ed32ddd86435e6529cff7084a13d6f20"}), "caf9266566bae157ba202810952add94", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the user should only see the right \"6\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "4151f7a0cd04fb54a4bf74d0c016df73",
                                                        "ed32ddd86435e6529cff7084a13d6f20"}), "7dceb5b985a98f5299904116e25a6b70", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the \"COB Booklet, COB Booklet, Defect106224HO, Making more of your money, Mortgag" +
                                                "e Provider List, Test\" of documents")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Documents", "3936857bb0b32a51b1c0114943f8f269"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Smoke", "1bb4f307bb933b53a6c47a0f83d848bc")}), new System.Collections.Generic.List<string>(new string[] {
                                        "a44af0c385c06f5b823f457f7cb36e0b",
                                        "ed32ddd86435e6529cff7084a13d6f20"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("3600fea474a67f5885abb1f74dcd4227", "Features/Documents.feature", "User is able to filter documents", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1753ae329ab48f50b5960c3b41b4f5fe"}), "e70975339754505c90426ecdf3051432", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user navigates to the Client Portal"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "7655e6bfd76f4851b9e301da670625c1"}), "85d36326898bba5b867d80d32b1075f9", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user is logged in"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "fabd29d7cc5bd55eb8d49715c3a3f1e3",
                                                        "d33b2b88b73f405091b028ff0147dbc5"}), "33f49c5cefa49b5c936f067a02c5c79f", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user clicks the \"My documents\" menu link"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "567043ec0cc6475ba0af1d1bc34d3d18",
                                                        "d33b2b88b73f405091b028ff0147dbc5"}), "305b773bfebf9d5c872d5121a2ecb2d8", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the user applies a \"Title (Z-A)\" on the Documents"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c5a8cdc97da528519f40bf1c22f241bd",
                                                        "d33b2b88b73f405091b028ff0147dbc5"}), "d87926a5c38b415a8dbee322bc23f8be", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the user should only see the right \"6\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "4151f7a0cd04fb54a4bf74d0c016df73",
                                                        "d33b2b88b73f405091b028ff0147dbc5"}), "6bcafe689c7703539cf23157c684db1c", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the \"Test, Mortgage Provider List, Making more of your money, Defect106224HO, COB" +
                                                " Booklet, COB Booklet\" of documents")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Documents", "3936857bb0b32a51b1c0114943f8f269"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Smoke", "1bb4f307bb933b53a6c47a0f83d848bc")}), new System.Collections.Generic.List<string>(new string[] {
                                        "a44af0c385c06f5b823f457f7cb36e0b",
                                        "d33b2b88b73f405091b028ff0147dbc5"}))});
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages(new global::System.Func<Io.Cucumber.Messages.Types.Source>(DocumentsPageFeature.SourceFunc), new global::System.Func<Io.Cucumber.Messages.Types.GherkinDocument>(DocumentsPageFeature.GherkinDocumentFunc), new global::System.Func<System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle>>(DocumentsPageFeature.PicklesFunc));
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("User is able to filter documents")]
        [global::NUnit.Framework.CategoryAttribute("Smoke")]
        [global::NUnit.Framework.TestCaseAttribute("All", "6", "Test, Mortgage Provider List, Making more of your money, Defect106224HO, COB Book" +
            "let, COB Booklet", "0", null)]
        [global::NUnit.Framework.TestCaseAttribute("Read", "2", "Mortgage Provider List, Making more of your money", "1", null)]
        [global::NUnit.Framework.TestCaseAttribute("Unread", "3", "Defect106224HO, COB Booklet, COB Booklet", "2", null)]
        [global::NUnit.Framework.TestCaseAttribute("My uploads", "1", "Test", "3", null)]
        [global::NUnit.Framework.TestCaseAttribute("Newest first", "6", "Test, Mortgage Provider List, Making more of your money, Defect106224HO, COB Book" +
            "let, COB Booklet", "4", null)]
        [global::NUnit.Framework.TestCaseAttribute("Oldest first", "6", "COB Booklet, COB Booklet, Defect106224HO, Making more of your money, Mortgage Pro" +
            "vider List, Test", "5", null)]
        [global::NUnit.Framework.TestCaseAttribute("Title (A-Z)", "6", "COB Booklet, COB Booklet, Defect106224HO, Making more of your money, Mortgage Pro" +
            "vider List, Test", "6", null)]
        [global::NUnit.Framework.TestCaseAttribute("Title (Z-A)", "6", "Test, Mortgage Provider List, Making more of your money, Defect106224HO, COB Book" +
            "let, COB Booklet", "7", null)]
        public async global::System.Threading.Tasks.Task UserIsAbleToFilterDocuments(string filter, string count, string list, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Smoke"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("filter", filter);
            argumentsOfScenario.Add("count", count);
            argumentsOfScenario.Add("list", list);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("User is able to filter documents", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("the user clicks the \"My documents\" menu link", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync(string.Format("the user applies a \"{0}\" on the Documents", filter), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync(string.Format("the user should only see the right \"{0}\"", count), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync(string.Format("the \"{0}\" of documents", list), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
