// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ClientPortal.PRAT.Acceptance.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Login")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("Login")]
    public partial class LoginFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "Login"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Login", "  As a registered user\n  I want to be able to log in and log out", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
            await testRunner.GivenAsync("the user navigates to the Client Portal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
        }
        
        private static global::Io.Cucumber.Messages.Types.Source SourceFunc()
        {
            return new global::Io.Cucumber.Messages.Types.Source("Features/Login.feature", @"@Login
Feature: Login
  As a registered user
  I want to be able to log in and log out

  Background:
    Given the user navigates to the Client Portal

  @Smoke @Login
  Scenario Outline: Login functionality with validation
    Given the user enters ""<login>"" credentials
    When the user submits the login form
    Then the login attempt was ""<status>""
    Examples:
      | login   | status       |
      | valid   | successful   |
      | invalid | unsuccessful |

  @Smoke
  Scenario Outline: Login field validation
    Given the user clears the cookie pop up
    When the user submits an ""<error>"" in the login form
    Then the user should see validation messages for ""<validation>""
    Examples:
      | error   | validation  |
      | empty   | empty login |
      | invalid | bad email   |

  @Smoke
  Scenario: Logout Functionality
    Given the user is logged in
    When the user clicks on the logout button
    Then the user navigates to the ""logout"" page", global::Io.Cucumber.Messages.Types.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN);
        }
        
        private static global::Io.Cucumber.Messages.Types.GherkinDocument GherkinDocumentFunc()
        {
            return new global::Io.Cucumber.Messages.Types.GherkinDocument("Features/Login.feature", new global::Io.Cucumber.Messages.Types.Feature(new global::Io.Cucumber.Messages.Types.Location(2, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(1, new System.Nullable<long>(1)), "@Login", "3eed27552051d75b96bfee8d2453ed73")}), "en-US", "Feature", "Login", "  As a registered user\n  I want to be able to log in and log out", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.FeatureChild>(new global::Io.Cucumber.Messages.Types.FeatureChild[] {
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, new global::Io.Cucumber.Messages.Types.Background(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(3)), "Background", "", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the user navigates to the Client Portal", null, null, "28a3b977789d045c9d7b0723be03c1e8")}), "24cda9dec45c285ca5a07177e86f66ae"), null),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(10, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(3)), "@Smoke", "856a3a6393171d5a91508cc367c4f6d7"),
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(10)), "@Login", "dd69c2a01a67ef55b6e0b16a3168346c")}), "Scenario Outline", "Login functionality with validation", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(11, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the user enters \"<login>\" credentials", null, null, "b92a3439c028c65589eecf0b95fd0203"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(12, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "the user submits the login form", null, null, "faef88e4884636539dc44d3ea7e53e7e"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the login attempt was \"<status>\"", null, null, "336e418249eb3652ab3d072f5f704d4a")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[] {
                                                    new global::Io.Cucumber.Messages.Types.Examples(new global::Io.Cucumber.Messages.Types.Location(14, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Examples", "", "", new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(9)), "login"),
                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(19)), "status")}), "94dfd598e5e2a55488572adbf5751720"), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableRow>(new global::Io.Cucumber.Messages.Types.TableRow[] {
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(9)), "valid"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(19)), "successful")}), "686d555475b77555adf2779ddb02530b"),
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(9)), "invalid"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(19)), "unsuccessful")}), "5c8d0ca5f1ac495887e62d63b5724e1f")}), "be6be4180531245192e5a7146938d5da")}), "e0b8019b149a485faace19ee761ed284")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(3)), "@Smoke", "d489ea2222522d5c8675741de130c0e3")}), "Scenario Outline", "Login field validation", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the user clears the cookie pop up", null, null, "c995513656e34851a16926f7731d4472"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(22, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "the user submits an \"<error>\" in the login form", null, null, "a73160d6827aad558e745e13be0f1867"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the user should see validation messages for \"<validation>\"", null, null, "70c5b71f89aaad589ccfed9ca01c21d4")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[] {
                                                    new global::Io.Cucumber.Messages.Types.Examples(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Examples", "", "", new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(9)), "error"),
                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(19)), "validation")}), "2051595c2e370e51a5bca96179c9c23e"), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableRow>(new global::Io.Cucumber.Messages.Types.TableRow[] {
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(26, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(26, new System.Nullable<long>(9)), "empty"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(26, new System.Nullable<long>(19)), "empty login")}), "f6cd72b94b5543508c24162440e75980"),
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(9)), "invalid"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(19)), "bad email")}), "03c1b9315163a154af7a54101f686afb")}), "2192cacce2c1945b960e7669af2ed03a")}), "e26cb9569be4635da76e0d98c102481e")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(30, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(29, new System.Nullable<long>(3)), "@Smoke", "097cdc9264bd56588c3461dc40e1d7a8")}), "Scenario", "Logout Functionality", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(31, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the user is logged in", null, null, "6e6c2f4a537621569baa7881d7bab074"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(32, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "the user clicks on the logout button", null, null, "537501e8812e6a5ab05fada89ee45ad2"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(33, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the user navigates to the \"logout\" page", null, null, "8a50c66e1bcc2b558e41e7666e2a4fd4")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "aee234fbfaca76508d7378563664e42b"))})), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Comment>(new global::Io.Cucumber.Messages.Types.Comment[0]));
        }
        
        private static global::System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle> PicklesFunc()
        {
            return new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Pickle>(new global::Io.Cucumber.Messages.Types.Pickle[] {
                        new global::Io.Cucumber.Messages.Types.Pickle("aa14643c27d79357bba44f0ad501dc0d", "Features/Login.feature", "Login functionality with validation", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "28a3b977789d045c9d7b0723be03c1e8"}), "b7625d1d79c6d35491f91a2f9b8068da", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user navigates to the Client Portal"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "b92a3439c028c65589eecf0b95fd0203",
                                                        "686d555475b77555adf2779ddb02530b"}), "dfc95d29a417de5aa78fd00fb4095155", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user enters \"valid\" credentials"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "faef88e4884636539dc44d3ea7e53e7e",
                                                        "686d555475b77555adf2779ddb02530b"}), "eb6dfb04e662d45a92cb77ba1278d235", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the user submits the login form"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "336e418249eb3652ab3d072f5f704d4a",
                                                        "686d555475b77555adf2779ddb02530b"}), "d8da0c04ba6af65d9850d9373cbbf38d", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the login attempt was \"successful\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Login", "3eed27552051d75b96bfee8d2453ed73"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Smoke", "856a3a6393171d5a91508cc367c4f6d7"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Login", "dd69c2a01a67ef55b6e0b16a3168346c")}), new System.Collections.Generic.List<string>(new string[] {
                                        "e0b8019b149a485faace19ee761ed284",
                                        "686d555475b77555adf2779ddb02530b"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("32ee95802a42e8579d6ece4fe32416cd", "Features/Login.feature", "Login functionality with validation", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "28a3b977789d045c9d7b0723be03c1e8"}), "9299b71c63f6195b94f4f42190873fa4", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user navigates to the Client Portal"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "b92a3439c028c65589eecf0b95fd0203",
                                                        "5c8d0ca5f1ac495887e62d63b5724e1f"}), "de8f5caa6f06b75a8436e7af68b55128", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user enters \"invalid\" credentials"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "faef88e4884636539dc44d3ea7e53e7e",
                                                        "5c8d0ca5f1ac495887e62d63b5724e1f"}), "ed5d6193da6d0c5ab5511751ed71ee17", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the user submits the login form"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "336e418249eb3652ab3d072f5f704d4a",
                                                        "5c8d0ca5f1ac495887e62d63b5724e1f"}), "4b63d9599c039c58ba0934572b592f6b", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the login attempt was \"unsuccessful\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Login", "3eed27552051d75b96bfee8d2453ed73"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Smoke", "856a3a6393171d5a91508cc367c4f6d7"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Login", "dd69c2a01a67ef55b6e0b16a3168346c")}), new System.Collections.Generic.List<string>(new string[] {
                                        "e0b8019b149a485faace19ee761ed284",
                                        "5c8d0ca5f1ac495887e62d63b5724e1f"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("3ed6413270f4cc5dbf617ed78129eeda", "Features/Login.feature", "Login field validation", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "28a3b977789d045c9d7b0723be03c1e8"}), "c227c3f5bec25d50b65943763c8c6def", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user navigates to the Client Portal"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c995513656e34851a16926f7731d4472",
                                                        "f6cd72b94b5543508c24162440e75980"}), "4b665e54ef3dae5495dc91ef7a5889e6", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user clears the cookie pop up"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a73160d6827aad558e745e13be0f1867",
                                                        "f6cd72b94b5543508c24162440e75980"}), "3a94a4045aebe35f808315d4a6c90a74", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the user submits an \"empty\" in the login form"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "70c5b71f89aaad589ccfed9ca01c21d4",
                                                        "f6cd72b94b5543508c24162440e75980"}), "9c3b49dc86f174539a3f939776bc9253", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the user should see validation messages for \"empty login\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Login", "3eed27552051d75b96bfee8d2453ed73"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Smoke", "d489ea2222522d5c8675741de130c0e3")}), new System.Collections.Generic.List<string>(new string[] {
                                        "e26cb9569be4635da76e0d98c102481e",
                                        "f6cd72b94b5543508c24162440e75980"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("ff353976b4a1ce57bc87d1bed9a74bf4", "Features/Login.feature", "Login field validation", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "28a3b977789d045c9d7b0723be03c1e8"}), "4753265a1beae6549b6c53f83a9adbac", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user navigates to the Client Portal"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c995513656e34851a16926f7731d4472",
                                                        "03c1b9315163a154af7a54101f686afb"}), "2b0ee23cd42eab5d85d49021347ab802", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user clears the cookie pop up"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a73160d6827aad558e745e13be0f1867",
                                                        "03c1b9315163a154af7a54101f686afb"}), "6f783a2d591c5253ab231ca51c0a3da5", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the user submits an \"invalid\" in the login form"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "70c5b71f89aaad589ccfed9ca01c21d4",
                                                        "03c1b9315163a154af7a54101f686afb"}), "16aabc4ae68a1c5187e237300872e08d", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the user should see validation messages for \"bad email\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Login", "3eed27552051d75b96bfee8d2453ed73"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Smoke", "d489ea2222522d5c8675741de130c0e3")}), new System.Collections.Generic.List<string>(new string[] {
                                        "e26cb9569be4635da76e0d98c102481e",
                                        "03c1b9315163a154af7a54101f686afb"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("f0032df211b1e152b169c0f3343e8695", "Features/Login.feature", "Logout Functionality", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "28a3b977789d045c9d7b0723be03c1e8"}), "203b68facc3cda5190bbfd66fc76572b", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user navigates to the Client Portal"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "6e6c2f4a537621569baa7881d7bab074"}), "714292af9f899c5a9f561ec1613deabd", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user is logged in"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "537501e8812e6a5ab05fada89ee45ad2"}), "1dc147e63f3b625391deba703d834987", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the user clicks on the logout button"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "8a50c66e1bcc2b558e41e7666e2a4fd4"}), "7232e69001aaf55b81e98eaf28603604", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the user navigates to the \"logout\" page")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Login", "3eed27552051d75b96bfee8d2453ed73"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Smoke", "097cdc9264bd56588c3461dc40e1d7a8")}), new System.Collections.Generic.List<string>(new string[] {
                                        "aee234fbfaca76508d7378563664e42b"}))});
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages(new global::System.Func<Io.Cucumber.Messages.Types.Source>(LoginFeature.SourceFunc), new global::System.Func<Io.Cucumber.Messages.Types.GherkinDocument>(LoginFeature.GherkinDocumentFunc), new global::System.Func<System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle>>(LoginFeature.PicklesFunc));
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Login functionality with validation")]
        [global::NUnit.Framework.CategoryAttribute("Smoke")]
        [global::NUnit.Framework.CategoryAttribute("Login")]
        [global::NUnit.Framework.TestCaseAttribute("valid", "successful", "0", null)]
        [global::NUnit.Framework.TestCaseAttribute("invalid", "unsuccessful", "1", null)]
        public async global::System.Threading.Tasks.Task LoginFunctionalityWithValidation(string login, string status, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Smoke",
                    "Login"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("login", login);
            argumentsOfScenario.Add("status", status);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Login functionality with validation", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync(string.Format("the user enters \"{0}\" credentials", login), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("the user submits the login form", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync(string.Format("the login attempt was \"{0}\"", status), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Login field validation")]
        [global::NUnit.Framework.CategoryAttribute("Smoke")]
        [global::NUnit.Framework.TestCaseAttribute("empty", "empty login", "2", null)]
        [global::NUnit.Framework.TestCaseAttribute("invalid", "bad email", "3", null)]
        public async global::System.Threading.Tasks.Task LoginFieldValidation(string error, string validation, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Smoke"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("error", error);
            argumentsOfScenario.Add("validation", validation);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Login field validation", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("the user clears the cookie pop up", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync(string.Format("the user submits an \"{0}\" in the login form", error), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync(string.Format("the user should see validation messages for \"{0}\"", validation), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Logout Functionality")]
        [global::NUnit.Framework.CategoryAttribute("Smoke")]
        public async global::System.Threading.Tasks.Task LogoutFunctionality()
        {
            string[] tagsOfScenario = new string[] {
                    "Smoke"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Logout Functionality", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("the user is logged in", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("the user clicks on the logout button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the user navigates to the \"logout\" page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
