// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ClientPortal.PRAT.Acceptance.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Login")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("Login")]
    public partial class LoginFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "Login"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Login", "  As a registered user\r\n  I want to be able to log in and log out", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
            await testRunner.GivenAsync("the user navigates to the Client Portal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
        }
        
        private static global::Io.Cucumber.Messages.Types.Source SourceFunc()
        {
            return new global::Io.Cucumber.Messages.Types.Source("Features/Login.feature", @"@Login
Feature: Login
  As a registered user
  I want to be able to log in and log out

  Background:
    Given the user navigates to the Client Portal

  @Smoke
  Scenario Outline: Login functionality with validation
    Given the user enters ""<login>"" credentials
    When the user submits the login form
    Then the login attempt was ""<status>""
    Examples:
      | login   | status       |
      | valid   | successful   |
      | invalid | unsuccessful |

  @Smoke
  Scenario Outline: Login field validation
    Given the user clears the cookie pop up
    When the user submits an ""<error>"" in the login form
    Then the user should see validation messages for ""<validation>""
    Examples:
      | error   | validation  |
      | empty   | empty login |
      | invalid | bad email   |

  @Smoke
  Scenario: Logout Functionality
    Given the user is logged in
    When the user clicks on the logout button
    Then the user navigates to the ""logout"" page", global::Io.Cucumber.Messages.Types.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN);
        }
        
        private static global::Io.Cucumber.Messages.Types.GherkinDocument GherkinDocumentFunc()
        {
            return new global::Io.Cucumber.Messages.Types.GherkinDocument("Features/Login.feature", new global::Io.Cucumber.Messages.Types.Feature(new global::Io.Cucumber.Messages.Types.Location(2, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(1, new System.Nullable<long>(1)), "@Login", "f43c92e81d0b6755958fefa316fca42e")}), "en-US", "Feature", "Login", "  As a registered user\r\n  I want to be able to log in and log out", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.FeatureChild>(new global::Io.Cucumber.Messages.Types.FeatureChild[] {
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, new global::Io.Cucumber.Messages.Types.Background(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(3)), "Background", "", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the user navigates to the Client Portal", null, null, "bb00350e0e08aa5cab752d9e0323688f")}), "af4519162f224a59a69328d2a0d731a3"), null),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(10, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(3)), "@Smoke", "8826c651929f9555bcca428049a145cf")}), "Scenario Outline", "Login functionality with validation", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(11, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the user enters \"<login>\" credentials", null, null, "2f760ba3eca7f853bf42514c0272e039"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(12, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "the user submits the login form", null, null, "3cb64e545546a95e942dcf7339c00239"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the login attempt was \"<status>\"", null, null, "e92bc0195bdf2957b66972c91ab76a6a")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[] {
                                                    new global::Io.Cucumber.Messages.Types.Examples(new global::Io.Cucumber.Messages.Types.Location(14, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Examples", "", "", new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(9)), "login"),
                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(19)), "status")}), "63de4eecd3a0f75193a12f5141eb39ae"), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableRow>(new global::Io.Cucumber.Messages.Types.TableRow[] {
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(9)), "valid"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(19)), "successful")}), "3a873a8517ba9c5eb8c6af67a2e0ec0a"),
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(9)), "invalid"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(19)), "unsuccessful")}), "6da718a3f546085fbb47a68816fa90e2")}), "37b9b0ea40041f538b51022f7f23292e")}), "126345ac0edd485487dc72832b8bb568")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(3)), "@Smoke", "7aa3a818e4b730509c68f81c3d871e5a")}), "Scenario Outline", "Login field validation", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the user clears the cookie pop up", null, null, "f97afd1a8cb6a65bb6fbfe7f8e218951"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(22, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "the user submits an \"<error>\" in the login form", null, null, "7e32e6550e9dd257a42b1b5cf5259cc1"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the user should see validation messages for \"<validation>\"", null, null, "f0b7a2d45b4fdf5b8520c69e850d659f")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[] {
                                                    new global::Io.Cucumber.Messages.Types.Examples(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Examples", "", "", new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(9)), "error"),
                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(19)), "validation")}), "e18db1a0730c1653bd51c2818c5f33db"), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableRow>(new global::Io.Cucumber.Messages.Types.TableRow[] {
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(26, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(26, new System.Nullable<long>(9)), "empty"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(26, new System.Nullable<long>(19)), "empty login")}), "b014fba58c9ebe5a9a1ecd9b90c316dc"),
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(9)), "invalid"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(19)), "bad email")}), "c5853b03638bb85281be742aebfff706")}), "aabf661ebcd062578d53a1810385f643")}), "248a6e9b87ddd55b80c855f0f19a533f")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(30, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(29, new System.Nullable<long>(3)), "@Smoke", "d934502302f41850844ab86572baa997")}), "Scenario", "Logout Functionality", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(31, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the user is logged in", null, null, "49904f318545f455b1aa817ebb7da9b8"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(32, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "the user clicks on the logout button", null, null, "0aec0bbbbd454f548eba36e5c6e01de9"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(33, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the user navigates to the \"logout\" page", null, null, "2346d7aaf876b65db8d0b57cc5c6d086")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "126f66fa1ceeff57ae5c9b49087c27f1"))})), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Comment>(new global::Io.Cucumber.Messages.Types.Comment[0]));
        }
        
        private static global::System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle> PicklesFunc()
        {
            return new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Pickle>(new global::Io.Cucumber.Messages.Types.Pickle[] {
                        new global::Io.Cucumber.Messages.Types.Pickle("44aab9e4025534579887a81490bc1ac2", "Features/Login.feature", "Login functionality with validation", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "bb00350e0e08aa5cab752d9e0323688f"}), "5aca1b7cdf55d056a0d23007eaf0e935", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user navigates to the Client Portal"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "2f760ba3eca7f853bf42514c0272e039",
                                                        "3a873a8517ba9c5eb8c6af67a2e0ec0a"}), "5ae25b3db573eb5ca1f8c4ee74cba430", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user enters \"valid\" credentials"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3cb64e545546a95e942dcf7339c00239",
                                                        "3a873a8517ba9c5eb8c6af67a2e0ec0a"}), "010d1610cdf13d5498db2bd73e4ce912", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the user submits the login form"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e92bc0195bdf2957b66972c91ab76a6a",
                                                        "3a873a8517ba9c5eb8c6af67a2e0ec0a"}), "ee2e926df6f184559d35753b4abb37a9", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the login attempt was \"successful\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Login", "f43c92e81d0b6755958fefa316fca42e"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Smoke", "8826c651929f9555bcca428049a145cf")}), new System.Collections.Generic.List<string>(new string[] {
                                        "126345ac0edd485487dc72832b8bb568",
                                        "3a873a8517ba9c5eb8c6af67a2e0ec0a"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("38bcd963cc21075dadf5cb8d405ddd4b", "Features/Login.feature", "Login functionality with validation", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "bb00350e0e08aa5cab752d9e0323688f"}), "8bb753879f4ca659b5ebf13219eeae3e", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user navigates to the Client Portal"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "2f760ba3eca7f853bf42514c0272e039",
                                                        "6da718a3f546085fbb47a68816fa90e2"}), "387e4073c67cde51b3f8b328372ac345", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user enters \"invalid\" credentials"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3cb64e545546a95e942dcf7339c00239",
                                                        "6da718a3f546085fbb47a68816fa90e2"}), "af5cde742a42d45d8dd22cdae8ea1cb9", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the user submits the login form"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e92bc0195bdf2957b66972c91ab76a6a",
                                                        "6da718a3f546085fbb47a68816fa90e2"}), "d1bc326b102db552ad6ba1b54c738883", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the login attempt was \"unsuccessful\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Login", "f43c92e81d0b6755958fefa316fca42e"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Smoke", "8826c651929f9555bcca428049a145cf")}), new System.Collections.Generic.List<string>(new string[] {
                                        "126345ac0edd485487dc72832b8bb568",
                                        "6da718a3f546085fbb47a68816fa90e2"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("f1e53f9bb6e97a5e8863c96625d2b3aa", "Features/Login.feature", "Login field validation", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "bb00350e0e08aa5cab752d9e0323688f"}), "b8cb11f78bea7458974d8d493835f395", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user navigates to the Client Portal"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f97afd1a8cb6a65bb6fbfe7f8e218951",
                                                        "b014fba58c9ebe5a9a1ecd9b90c316dc"}), "48c60002e49c6e55bd44ed0904de857c", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user clears the cookie pop up"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "7e32e6550e9dd257a42b1b5cf5259cc1",
                                                        "b014fba58c9ebe5a9a1ecd9b90c316dc"}), "a146fe7ac390f8558cd5fe63778a2a35", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the user submits an \"empty\" in the login form"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f0b7a2d45b4fdf5b8520c69e850d659f",
                                                        "b014fba58c9ebe5a9a1ecd9b90c316dc"}), "56f53a471bc4ec5dbfca6f77f39fa702", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the user should see validation messages for \"empty login\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Login", "f43c92e81d0b6755958fefa316fca42e"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Smoke", "7aa3a818e4b730509c68f81c3d871e5a")}), new System.Collections.Generic.List<string>(new string[] {
                                        "248a6e9b87ddd55b80c855f0f19a533f",
                                        "b014fba58c9ebe5a9a1ecd9b90c316dc"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("a9b46130ce4e7254ac7a135f3a76588c", "Features/Login.feature", "Login field validation", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "bb00350e0e08aa5cab752d9e0323688f"}), "7fea403065a2b557a6886f3ef78282b9", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user navigates to the Client Portal"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f97afd1a8cb6a65bb6fbfe7f8e218951",
                                                        "c5853b03638bb85281be742aebfff706"}), "4a5bc861ff6584538c19ad870fe1156f", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user clears the cookie pop up"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "7e32e6550e9dd257a42b1b5cf5259cc1",
                                                        "c5853b03638bb85281be742aebfff706"}), "6c66b25d794f185480611e3ef3efc7c1", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the user submits an \"invalid\" in the login form"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f0b7a2d45b4fdf5b8520c69e850d659f",
                                                        "c5853b03638bb85281be742aebfff706"}), "04c3bae8ec7fc75781cf6522bcbdf499", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the user should see validation messages for \"bad email\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Login", "f43c92e81d0b6755958fefa316fca42e"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Smoke", "7aa3a818e4b730509c68f81c3d871e5a")}), new System.Collections.Generic.List<string>(new string[] {
                                        "248a6e9b87ddd55b80c855f0f19a533f",
                                        "c5853b03638bb85281be742aebfff706"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("222e667a59d3b155be336370f8695e3c", "Features/Login.feature", "Logout Functionality", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "bb00350e0e08aa5cab752d9e0323688f"}), "4cf4a99d9a556e5692f3197e2085d61a", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user navigates to the Client Portal"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "49904f318545f455b1aa817ebb7da9b8"}), "460efcbd44866b5eb2dae8f5d6dd1ce0", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user is logged in"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "0aec0bbbbd454f548eba36e5c6e01de9"}), "82012325038cfe5893723b9d245381d1", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the user clicks on the logout button"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "2346d7aaf876b65db8d0b57cc5c6d086"}), "d1895add11ec605f8dc175971b4d4e15", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the user navigates to the \"logout\" page")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Login", "f43c92e81d0b6755958fefa316fca42e"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Smoke", "d934502302f41850844ab86572baa997")}), new System.Collections.Generic.List<string>(new string[] {
                                        "126f66fa1ceeff57ae5c9b49087c27f1"}))});
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages(new global::System.Func<Io.Cucumber.Messages.Types.Source>(LoginFeature.SourceFunc), new global::System.Func<Io.Cucumber.Messages.Types.GherkinDocument>(LoginFeature.GherkinDocumentFunc), new global::System.Func<System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle>>(LoginFeature.PicklesFunc));
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Login functionality with validation")]
        [global::NUnit.Framework.CategoryAttribute("Smoke")]
        [global::NUnit.Framework.TestCaseAttribute("valid", "successful", "0", null)]
        [global::NUnit.Framework.TestCaseAttribute("invalid", "unsuccessful", "1", null)]
        public async global::System.Threading.Tasks.Task LoginFunctionalityWithValidation(string login, string status, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Smoke"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("login", login);
            argumentsOfScenario.Add("status", status);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Login functionality with validation", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync(string.Format("the user enters \"{0}\" credentials", login), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("the user submits the login form", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync(string.Format("the login attempt was \"{0}\"", status), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Login field validation")]
        [global::NUnit.Framework.CategoryAttribute("Smoke")]
        [global::NUnit.Framework.TestCaseAttribute("empty", "empty login", "2", null)]
        [global::NUnit.Framework.TestCaseAttribute("invalid", "bad email", "3", null)]
        public async global::System.Threading.Tasks.Task LoginFieldValidation(string error, string validation, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Smoke"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("error", error);
            argumentsOfScenario.Add("validation", validation);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Login field validation", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("the user clears the cookie pop up", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync(string.Format("the user submits an \"{0}\" in the login form", error), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync(string.Format("the user should see validation messages for \"{0}\"", validation), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Logout Functionality")]
        [global::NUnit.Framework.CategoryAttribute("Smoke")]
        public async global::System.Threading.Tasks.Task LogoutFunctionality()
        {
            string[] tagsOfScenario = new string[] {
                    "Smoke"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Logout Functionality", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("the user is logged in", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("the user clicks on the logout button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the user navigates to the \"logout\" page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
