// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ClientPortal.PRAT.Acceptance.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Navigation")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("Navigation")]
    public partial class NavigationFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "Navigation"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Navigation", "  As a registered user\n  I want to be able to verify all pages exist and are navi" +
                "gable", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
            await testRunner.GivenAsync("the user navigates to the Client Portal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
        }
        
        private static global::Io.Cucumber.Messages.Types.Source SourceFunc()
        {
            return new global::Io.Cucumber.Messages.Types.Source("Features/Navigation.feature", @"@Navigation
Feature: Navigation
  As a registered user
  I want to be able to verify all pages exist and are navigable

  Background:
  Given the user navigates to the Client Portal

  @Smoke
  Scenario Outline: Navigation after login
    Given the user is logged in
    When the user clicks the ""<page>"" menu link
    Then the user navigates to the ""<page>"" page
    Examples:
    | page                 |
    | My notifications     |
    | My profile           |
    | My documents         |
    | Privacy policy       |
    | Terms and conditions |
    | Cookie policy        |

Rule: Cookie page
  Background:
    Given the user clears the cookie pop up

  @Smoke
  Scenario: Navigation password reset
    Then the user navigates to the ""Password reset"" page

  @Smoke
  Scenario: Navigation login page
    Then the user navigates to the ""Login"" page", global::Io.Cucumber.Messages.Types.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN);
        }
        
        private static global::Io.Cucumber.Messages.Types.GherkinDocument GherkinDocumentFunc()
        {
            return new global::Io.Cucumber.Messages.Types.GherkinDocument("Features/Navigation.feature", new global::Io.Cucumber.Messages.Types.Feature(new global::Io.Cucumber.Messages.Types.Location(2, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(1, new System.Nullable<long>(1)), "@Navigation", "e22961e8a6ee2850b75a2b979e78a0ae")}), "en-US", "Feature", "Navigation", "  As a registered user\n  I want to be able to verify all pages exist and are navi" +
                        "gable", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.FeatureChild>(new global::Io.Cucumber.Messages.Types.FeatureChild[] {
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, new global::Io.Cucumber.Messages.Types.Background(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(3)), "Background", "", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(3)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the user navigates to the Client Portal", null, null, "4f455afc34044a54ae423739db9ca363")}), "ecc645156ffd7e5495c0a868231ba1af"), null),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(10, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(3)), "@Smoke", "6388383fc8f6ae54b6c4739b97c151f3")}), "Scenario Outline", "Navigation after login", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(11, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the user is logged in", null, null, "81f63cd38944f75497fce80bab2af2bd"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(12, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "the user clicks the \"<page>\" menu link", null, null, "55eda4cc708f1a5fa4d6d58548f98719"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the user navigates to the \"<page>\" page", null, null, "c556c4d5ef4426528aa72573bc701591")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[] {
                                                    new global::Io.Cucumber.Messages.Types.Examples(new global::Io.Cucumber.Messages.Types.Location(14, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Examples", "", "", new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(7)), "page")}), "d5351bdc5b88a356932ff8f4a832c134"), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableRow>(new global::Io.Cucumber.Messages.Types.TableRow[] {
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(7)), "My notifications")}), "ad6d7ceeedd6fb53a2e007dec1bc87d2"),
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(7)), "My profile")}), "67fcbbec2b37725cac59e2667a419626"),
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(7)), "My documents")}), "760d3d4f90eea352b789c82ea63e6356"),
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(7)), "Privacy policy")}), "1592253e9a55795daef29c1492ce2711"),
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(7)), "Terms and conditions")}), "a2bc7c2a498d2853b0646472f7c04c9f"),
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(7)), "Cookie policy")}), "0ecdf811c3d6305fb58b70647eec31b2")}), "c7d6263933b70d56a80b9bf6926786cf")}), "e6c1cbe4fcd4785592cf1895a120feba")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(new global::Io.Cucumber.Messages.Types.Rule(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Rule", "Cookie page", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.RuleChild>(new global::Io.Cucumber.Messages.Types.RuleChild[] {
                                                    new global::Io.Cucumber.Messages.Types.RuleChild(new global::Io.Cucumber.Messages.Types.Background(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(3)), "Background", "", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                                        new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the user clears the cookie pop up", null, null, "b35d1faaf0764d538ef99cdaab420496")}), "b4669fa827c0f65799d3ef034d7aafde"), null),
                                                    new global::Io.Cucumber.Messages.Types.RuleChild(null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(28, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                                        new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(3)), "@Smoke", "178dfc5232af05598a5d33560ae8947f")}), "Scenario", "Navigation password reset", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                                        new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(29, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the user navigates to the \"Password reset\" page", null, null, "677f314469d63156ae4c76e39582ce7a")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "11accf066162fe5fb7c9aee73e3f7265")),
                                                    new global::Io.Cucumber.Messages.Types.RuleChild(null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(32, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                                        new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(31, new System.Nullable<long>(3)), "@Smoke", "84e67de2fa6cae5aa9c47299ee0ae3d3")}), "Scenario", "Navigation login page", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                                        new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(33, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the user navigates to the \"Login\" page", null, null, "28c715cc6a843858b9c41e8d344d3ce2")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "b73233ffeab9855ba8d0768f03fb976e"))}), "257543892a3dbc5eb140b5685b485ebb"), null, null)})), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Comment>(new global::Io.Cucumber.Messages.Types.Comment[0]));
        }
        
        private static global::System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle> PicklesFunc()
        {
            return new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Pickle>(new global::Io.Cucumber.Messages.Types.Pickle[] {
                        new global::Io.Cucumber.Messages.Types.Pickle("2dada4fd3cb62952b79d964e9957d400", "Features/Navigation.feature", "Navigation after login", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "4f455afc34044a54ae423739db9ca363"}), "42bb5ac0716d1a509cec5f317e5bb21c", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user navigates to the Client Portal"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "81f63cd38944f75497fce80bab2af2bd",
                                                        "ad6d7ceeedd6fb53a2e007dec1bc87d2"}), "058009bfa2bc4c5389cfcbd179652057", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user is logged in"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "55eda4cc708f1a5fa4d6d58548f98719",
                                                        "ad6d7ceeedd6fb53a2e007dec1bc87d2"}), "8407f92404f10f5696ac06d305bdbb48", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the user clicks the \"My notifications\" menu link"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c556c4d5ef4426528aa72573bc701591",
                                                        "ad6d7ceeedd6fb53a2e007dec1bc87d2"}), "258126abcaa7ca529bb2f9cbefdb1daa", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the user navigates to the \"My notifications\" page")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Navigation", "e22961e8a6ee2850b75a2b979e78a0ae"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Smoke", "6388383fc8f6ae54b6c4739b97c151f3")}), new System.Collections.Generic.List<string>(new string[] {
                                        "e6c1cbe4fcd4785592cf1895a120feba",
                                        "ad6d7ceeedd6fb53a2e007dec1bc87d2"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("a7c20459b06f925185233cd053525e74", "Features/Navigation.feature", "Navigation after login", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "4f455afc34044a54ae423739db9ca363"}), "577ed02bab1dce56baee7435890d05ef", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user navigates to the Client Portal"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "81f63cd38944f75497fce80bab2af2bd",
                                                        "67fcbbec2b37725cac59e2667a419626"}), "f3d9a070a51e4a569f5424754c409baf", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user is logged in"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "55eda4cc708f1a5fa4d6d58548f98719",
                                                        "67fcbbec2b37725cac59e2667a419626"}), "9ce5a001d4f0105583d49eb4427878a6", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the user clicks the \"My profile\" menu link"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c556c4d5ef4426528aa72573bc701591",
                                                        "67fcbbec2b37725cac59e2667a419626"}), "9bf0a707b5cd3653958858131d06c945", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the user navigates to the \"My profile\" page")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Navigation", "e22961e8a6ee2850b75a2b979e78a0ae"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Smoke", "6388383fc8f6ae54b6c4739b97c151f3")}), new System.Collections.Generic.List<string>(new string[] {
                                        "e6c1cbe4fcd4785592cf1895a120feba",
                                        "67fcbbec2b37725cac59e2667a419626"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("7c887e903e4c1a5aa91def9416ed0e9a", "Features/Navigation.feature", "Navigation after login", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "4f455afc34044a54ae423739db9ca363"}), "8bdd0cd178969458ad313d676285043d", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user navigates to the Client Portal"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "81f63cd38944f75497fce80bab2af2bd",
                                                        "760d3d4f90eea352b789c82ea63e6356"}), "1d2660509e7bbb5691ae84a867cfcb86", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user is logged in"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "55eda4cc708f1a5fa4d6d58548f98719",
                                                        "760d3d4f90eea352b789c82ea63e6356"}), "8c7835bfd742f3508597bb66d33d90e7", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the user clicks the \"My documents\" menu link"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c556c4d5ef4426528aa72573bc701591",
                                                        "760d3d4f90eea352b789c82ea63e6356"}), "ae286e553c0904578d5ece76a39b0cdc", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the user navigates to the \"My documents\" page")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Navigation", "e22961e8a6ee2850b75a2b979e78a0ae"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Smoke", "6388383fc8f6ae54b6c4739b97c151f3")}), new System.Collections.Generic.List<string>(new string[] {
                                        "e6c1cbe4fcd4785592cf1895a120feba",
                                        "760d3d4f90eea352b789c82ea63e6356"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("a93ed4582309aa508e675ae4edccd8c7", "Features/Navigation.feature", "Navigation after login", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "4f455afc34044a54ae423739db9ca363"}), "b0885d38c9d76f51909a7c1510476db3", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user navigates to the Client Portal"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "81f63cd38944f75497fce80bab2af2bd",
                                                        "1592253e9a55795daef29c1492ce2711"}), "2b75b7c106a84b5fad319ac7a583593c", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user is logged in"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "55eda4cc708f1a5fa4d6d58548f98719",
                                                        "1592253e9a55795daef29c1492ce2711"}), "08a1c86839512d5bbfacc1dbdb5e1cf9", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the user clicks the \"Privacy policy\" menu link"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c556c4d5ef4426528aa72573bc701591",
                                                        "1592253e9a55795daef29c1492ce2711"}), "75f5b34eb53e045fbbf7e073c9bd413d", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the user navigates to the \"Privacy policy\" page")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Navigation", "e22961e8a6ee2850b75a2b979e78a0ae"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Smoke", "6388383fc8f6ae54b6c4739b97c151f3")}), new System.Collections.Generic.List<string>(new string[] {
                                        "e6c1cbe4fcd4785592cf1895a120feba",
                                        "1592253e9a55795daef29c1492ce2711"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("6bf0d68b7c3ab45a9d8f365672c1bbed", "Features/Navigation.feature", "Navigation after login", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "4f455afc34044a54ae423739db9ca363"}), "3ee9aa92c473165cb85dc106d962b473", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user navigates to the Client Portal"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "81f63cd38944f75497fce80bab2af2bd",
                                                        "a2bc7c2a498d2853b0646472f7c04c9f"}), "72dbfb5d23ff87548dc5447cfe2b1790", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user is logged in"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "55eda4cc708f1a5fa4d6d58548f98719",
                                                        "a2bc7c2a498d2853b0646472f7c04c9f"}), "51d39e7e89f92a52bea2e67c9851a407", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the user clicks the \"Terms and conditions\" menu link"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c556c4d5ef4426528aa72573bc701591",
                                                        "a2bc7c2a498d2853b0646472f7c04c9f"}), "a8ef7c2fd7fc30568d9ca239cf2604ac", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the user navigates to the \"Terms and conditions\" page")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Navigation", "e22961e8a6ee2850b75a2b979e78a0ae"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Smoke", "6388383fc8f6ae54b6c4739b97c151f3")}), new System.Collections.Generic.List<string>(new string[] {
                                        "e6c1cbe4fcd4785592cf1895a120feba",
                                        "a2bc7c2a498d2853b0646472f7c04c9f"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("a124d90a5fe90e5eb7bb2bc589daaeed", "Features/Navigation.feature", "Navigation after login", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "4f455afc34044a54ae423739db9ca363"}), "183b7981025d385cb9abf8fda9ebf6a9", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user navigates to the Client Portal"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "81f63cd38944f75497fce80bab2af2bd",
                                                        "0ecdf811c3d6305fb58b70647eec31b2"}), "0e51a7e72f783e58a6091e72d552ae25", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user is logged in"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "55eda4cc708f1a5fa4d6d58548f98719",
                                                        "0ecdf811c3d6305fb58b70647eec31b2"}), "bb1b9b7c45798b5088b7a7a44fb1518b", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the user clicks the \"Cookie policy\" menu link"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c556c4d5ef4426528aa72573bc701591",
                                                        "0ecdf811c3d6305fb58b70647eec31b2"}), "63ce13a6239358589eaf149f10c69828", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the user navigates to the \"Cookie policy\" page")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Navigation", "e22961e8a6ee2850b75a2b979e78a0ae"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Smoke", "6388383fc8f6ae54b6c4739b97c151f3")}), new System.Collections.Generic.List<string>(new string[] {
                                        "e6c1cbe4fcd4785592cf1895a120feba",
                                        "0ecdf811c3d6305fb58b70647eec31b2"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("9c17ba4ea4f2f45785e0f82a07107e42", "Features/Navigation.feature", "Navigation password reset", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "4f455afc34044a54ae423739db9ca363"}), "78a9230b408d5e5080ecce7234524e2f", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user navigates to the Client Portal"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "b35d1faaf0764d538ef99cdaab420496"}), "c3613999cf528d56ae33f7672d0ad1f5", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user clears the cookie pop up"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "677f314469d63156ae4c76e39582ce7a"}), "7074620944376a5c94bcc4e72e3851fd", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the user navigates to the \"Password reset\" page")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Navigation", "e22961e8a6ee2850b75a2b979e78a0ae"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Smoke", "178dfc5232af05598a5d33560ae8947f")}), new System.Collections.Generic.List<string>(new string[] {
                                        "11accf066162fe5fb7c9aee73e3f7265"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("09815dc4e3891e51878c2b393fd28e1d", "Features/Navigation.feature", "Navigation login page", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "4f455afc34044a54ae423739db9ca363"}), "9a9e67d4200e8d5f865c8476b71c07d4", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user navigates to the Client Portal"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "b35d1faaf0764d538ef99cdaab420496"}), "74358082b129b158a03b2e6f2e8b0615", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user clears the cookie pop up"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "28c715cc6a843858b9c41e8d344d3ce2"}), "5345440453478755a35f7148ce0a1b22", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the user navigates to the \"Login\" page")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Navigation", "e22961e8a6ee2850b75a2b979e78a0ae"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Smoke", "84e67de2fa6cae5aa9c47299ee0ae3d3")}), new System.Collections.Generic.List<string>(new string[] {
                                        "b73233ffeab9855ba8d0768f03fb976e"}))});
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages(new global::System.Func<Io.Cucumber.Messages.Types.Source>(NavigationFeature.SourceFunc), new global::System.Func<Io.Cucumber.Messages.Types.GherkinDocument>(NavigationFeature.GherkinDocumentFunc), new global::System.Func<System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle>>(NavigationFeature.PicklesFunc));
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Navigation after login")]
        [global::NUnit.Framework.CategoryAttribute("Smoke")]
        [global::NUnit.Framework.TestCaseAttribute("My notifications", "0", null)]
        [global::NUnit.Framework.TestCaseAttribute("My profile", "1", null)]
        [global::NUnit.Framework.TestCaseAttribute("My documents", "2", null)]
        [global::NUnit.Framework.TestCaseAttribute("Privacy policy", "3", null)]
        [global::NUnit.Framework.TestCaseAttribute("Terms and conditions", "4", null)]
        [global::NUnit.Framework.TestCaseAttribute("Cookie policy", "5", null)]
        public async global::System.Threading.Tasks.Task NavigationAfterLogin(string page, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Smoke"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("page", page);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Navigation after login", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("the user is logged in", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync(string.Format("the user clicks the \"{0}\" menu link", page), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync(string.Format("the user navigates to the \"{0}\" page", page), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Navigation password reset")]
        [global::NUnit.Framework.CategoryAttribute("Smoke")]
        public async global::System.Threading.Tasks.Task NavigationPasswordReset()
        {
            string[] tagsOfScenario = new string[] {
                    "Smoke"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Navigation password reset", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Cookie page", null, tagsOfRule);
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("the user clears the cookie pop up", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.ThenAsync("the user navigates to the \"Password reset\" page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Navigation login page")]
        [global::NUnit.Framework.CategoryAttribute("Smoke")]
        public async global::System.Threading.Tasks.Task NavigationLoginPage()
        {
            string[] tagsOfScenario = new string[] {
                    "Smoke"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Navigation login page", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Cookie page", null, tagsOfRule);
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("the user clears the cookie pop up", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.ThenAsync("the user navigates to the \"Login\" page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
