// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ClientPortal.PRAT.Acceptance.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Password Reset")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("PasswordReset")]
    public partial class PasswordResetFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "PasswordReset"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Password Reset", "  As a registered user\n  I want to be able to reset my password at any time", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
            await testRunner.GivenAsync("the user navigates to the Client Portal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
            await testRunner.AndAsync("the user clears the cookie pop up", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            await testRunner.WhenAsync("the user navigates to the \"password reset\" page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
        }
        
        private static global::Io.Cucumber.Messages.Types.Source SourceFunc()
        {
            return new global::Io.Cucumber.Messages.Types.Source("Features/PasswordReset.feature", @"@PasswordReset
Feature: Password Reset
  As a registered user
  I want to be able to reset my password at any time

  Background:
    Given the user navigates to the Client Portal
    And the user clears the cookie pop up
    When the user navigates to the ""password reset"" page

  @Smoke
  Scenario Outline: Password reset validation
    When the user submits an ""<error>"" in the reset form
    Then the user should see validation messages for ""<validation>""
    Examples:
      | error   | validation         |
      | empty   | email required     |
      | invalid | bad email password |

  @Smoke
  Scenario: Cancel Password Reset
    When the user uses the ""password back"" button
    Then the user navigates to the ""login"" page

  @Smoke
  Scenario: Password Reset
    When the user submits a valid email
    Then the user is presented with a confirmation message", global::Io.Cucumber.Messages.Types.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN);
        }
        
        private static global::Io.Cucumber.Messages.Types.GherkinDocument GherkinDocumentFunc()
        {
            return new global::Io.Cucumber.Messages.Types.GherkinDocument("Features/PasswordReset.feature", new global::Io.Cucumber.Messages.Types.Feature(new global::Io.Cucumber.Messages.Types.Location(2, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(1, new System.Nullable<long>(1)), "@PasswordReset", "fd977a4997adfc51a654d4557f572340")}), "en-US", "Feature", "Password Reset", "  As a registered user\n  I want to be able to reset my password at any time", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.FeatureChild>(new global::Io.Cucumber.Messages.Types.FeatureChild[] {
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, new global::Io.Cucumber.Messages.Types.Background(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(3)), "Background", "", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the user navigates to the Client Portal", null, null, "70487ae523e0d65b85921d4856b3e7a3"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(8, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the user clears the cookie pop up", null, null, "b9ae0656ce259851ac7c3b6ab687a017"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "the user navigates to the \"password reset\" page", null, null, "9056dc56e0397b5aa06715479d596474")}), "7ce8389014239f5f9958ae5e00e31537"), null),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(12, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(11, new System.Nullable<long>(3)), "@Smoke", "fcf8af9e91f17b5298aeca39e27babe8")}), "Scenario Outline", "Password reset validation", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "the user submits an \"<error>\" in the reset form", null, null, "90dca506a29f875bbc9f89e1db8e9ec8"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(14, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the user should see validation messages for \"<validation>\"", null, null, "4916895d4cf5135eb133b53a9eb8a3bd")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[] {
                                                    new global::Io.Cucumber.Messages.Types.Examples(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Examples", "", "", new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(9)), "error"),
                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(19)), "validation")}), "a775e9b36b5a6959b228e6f9ef3c11cf"), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableRow>(new global::Io.Cucumber.Messages.Types.TableRow[] {
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(9)), "empty"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(19)), "email required")}), "b20f34b915364153a6ef3008be2b2238"),
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(9)), "invalid"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(19)), "bad email password")}), "baf17eb849e4b05499d427659eacaa08")}), "b81c09753e08ce5fa3d595faf52cc0e3")}), "da45e1abbc3f775ea751614505d11e5f")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(3)), "@Smoke", "33f1cee932c3cb51bc0e5a041062ce24")}), "Scenario", "Cancel Password Reset", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(22, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "the user uses the \"password back\" button", null, null, "f22a2106869f0152b2f8692ea3c6210d"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the user navigates to the \"login\" page", null, null, "2860f4830117a8568ab5cc5adc4be000")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "3ce80a659d252f568f2b5c14dfa5b687")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(26, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(3)), "@Smoke", "d4449cc34d71d753be2eb7fefd99bf6b")}), "Scenario", "Password Reset", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "the user submits a valid email", null, null, "057e863b72bc4b5dace3f3ed458583a7"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(28, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the user is presented with a confirmation message", null, null, "07a5161885d9f056975a4067d12d380b")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "330ebc845f2aef5c9d1e1356088984d4"))})), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Comment>(new global::Io.Cucumber.Messages.Types.Comment[0]));
        }
        
        private static global::System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle> PicklesFunc()
        {
            return new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Pickle>(new global::Io.Cucumber.Messages.Types.Pickle[] {
                        new global::Io.Cucumber.Messages.Types.Pickle("ab6d6abe4c5a94558e8dfd0d3a8b03d7", "Features/PasswordReset.feature", "Password reset validation", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "70487ae523e0d65b85921d4856b3e7a3"}), "3560fb128e44235ea35fe7e10a8d84fb", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user navigates to the Client Portal"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "b9ae0656ce259851ac7c3b6ab687a017"}), "e349c28cc431f85285cc354989ca4b54", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user clears the cookie pop up"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "9056dc56e0397b5aa06715479d596474"}), "8094cd5905dfb35d8223dab4f19a49b3", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the user navigates to the \"password reset\" page"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "90dca506a29f875bbc9f89e1db8e9ec8",
                                                        "b20f34b915364153a6ef3008be2b2238"}), "9efc8be56ff5845aa83aae84fb344495", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the user submits an \"empty\" in the reset form"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "4916895d4cf5135eb133b53a9eb8a3bd",
                                                        "b20f34b915364153a6ef3008be2b2238"}), "9392f121d0db105a8d37d54555517869", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the user should see validation messages for \"email required\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@PasswordReset", "fd977a4997adfc51a654d4557f572340"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Smoke", "fcf8af9e91f17b5298aeca39e27babe8")}), new System.Collections.Generic.List<string>(new string[] {
                                        "da45e1abbc3f775ea751614505d11e5f",
                                        "b20f34b915364153a6ef3008be2b2238"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("21f1d2d35045cd53b19b53c02fea6e81", "Features/PasswordReset.feature", "Password reset validation", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "70487ae523e0d65b85921d4856b3e7a3"}), "ad62c0091f05ae5b915c090cb9337ff4", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user navigates to the Client Portal"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "b9ae0656ce259851ac7c3b6ab687a017"}), "0cdc611597a99b51b6dd4a3d7840af32", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user clears the cookie pop up"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "9056dc56e0397b5aa06715479d596474"}), "6fafd14d43f38854be982616b15efe08", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the user navigates to the \"password reset\" page"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "90dca506a29f875bbc9f89e1db8e9ec8",
                                                        "baf17eb849e4b05499d427659eacaa08"}), "9338b26c74a2ee5b9a759dea18fbbacd", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the user submits an \"invalid\" in the reset form"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "4916895d4cf5135eb133b53a9eb8a3bd",
                                                        "baf17eb849e4b05499d427659eacaa08"}), "6c6f634b137d795292e2c919e7fd7aec", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the user should see validation messages for \"bad email password\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@PasswordReset", "fd977a4997adfc51a654d4557f572340"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Smoke", "fcf8af9e91f17b5298aeca39e27babe8")}), new System.Collections.Generic.List<string>(new string[] {
                                        "da45e1abbc3f775ea751614505d11e5f",
                                        "baf17eb849e4b05499d427659eacaa08"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("b8e4ee262fdbb25ca621da3eefd52786", "Features/PasswordReset.feature", "Cancel Password Reset", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "70487ae523e0d65b85921d4856b3e7a3"}), "a30e64cfaa1def588d68103b227e1f9f", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user navigates to the Client Portal"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "b9ae0656ce259851ac7c3b6ab687a017"}), "e206bbb51e48a25a85908818a54b3192", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user clears the cookie pop up"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "9056dc56e0397b5aa06715479d596474"}), "0351a32fd9fc1a58b3fd48e7ab3e5e8d", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the user navigates to the \"password reset\" page"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f22a2106869f0152b2f8692ea3c6210d"}), "7c24db9e9f88815e8095cfbcaaa32d74", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the user uses the \"password back\" button"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "2860f4830117a8568ab5cc5adc4be000"}), "f6bd0a272677e95fbdfb50b7906dec9a", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the user navigates to the \"login\" page")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@PasswordReset", "fd977a4997adfc51a654d4557f572340"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Smoke", "33f1cee932c3cb51bc0e5a041062ce24")}), new System.Collections.Generic.List<string>(new string[] {
                                        "3ce80a659d252f568f2b5c14dfa5b687"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("404cc6f170a21d589d48bcabc2654473", "Features/PasswordReset.feature", "Password Reset", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "70487ae523e0d65b85921d4856b3e7a3"}), "e219aff0119db7538aa2085d9eff8d7b", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user navigates to the Client Portal"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "b9ae0656ce259851ac7c3b6ab687a017"}), "00b056f19997ee5098dc5884ab6b970a", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the user clears the cookie pop up"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "9056dc56e0397b5aa06715479d596474"}), "ae68ff15fd29bd53a58d5128a0f506ce", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the user navigates to the \"password reset\" page"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "057e863b72bc4b5dace3f3ed458583a7"}), "02e094aea938cf50891136a9e153b2c0", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the user submits a valid email"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "07a5161885d9f056975a4067d12d380b"}), "339dddfb3c59f35796d5ec8d65ca917f", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the user is presented with a confirmation message")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@PasswordReset", "fd977a4997adfc51a654d4557f572340"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Smoke", "d4449cc34d71d753be2eb7fefd99bf6b")}), new System.Collections.Generic.List<string>(new string[] {
                                        "330ebc845f2aef5c9d1e1356088984d4"}))});
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages(new global::System.Func<Io.Cucumber.Messages.Types.Source>(PasswordResetFeature.SourceFunc), new global::System.Func<Io.Cucumber.Messages.Types.GherkinDocument>(PasswordResetFeature.GherkinDocumentFunc), new global::System.Func<System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle>>(PasswordResetFeature.PicklesFunc));
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Password reset validation")]
        [global::NUnit.Framework.CategoryAttribute("Smoke")]
        [global::NUnit.Framework.TestCaseAttribute("empty", "email required", "0", null)]
        [global::NUnit.Framework.TestCaseAttribute("invalid", "bad email password", "1", null)]
        public async global::System.Threading.Tasks.Task PasswordResetValidation(string error, string validation, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Smoke"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("error", error);
            argumentsOfScenario.Add("validation", validation);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Password reset validation", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.WhenAsync(string.Format("the user submits an \"{0}\" in the reset form", error), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync(string.Format("the user should see validation messages for \"{0}\"", validation), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Cancel Password Reset")]
        [global::NUnit.Framework.CategoryAttribute("Smoke")]
        public async global::System.Threading.Tasks.Task CancelPasswordReset()
        {
            string[] tagsOfScenario = new string[] {
                    "Smoke"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cancel Password Reset", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.WhenAsync("the user uses the \"password back\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the user navigates to the \"login\" page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Password Reset")]
        [global::NUnit.Framework.CategoryAttribute("Smoke")]
        public async global::System.Threading.Tasks.Task PasswordReset()
        {
            string[] tagsOfScenario = new string[] {
                    "Smoke"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Password Reset", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.WhenAsync("the user submits a valid email", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the user is presented with a confirmation message", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
